name = "web"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "supermemory"
database_id = "4f9d583e-4da6-4494-ac6c-d5a2207d64a1"

[[unsafe.bindings]]
name = "RATELIMITER"
type = "ratelimit"
namespace_id = "1001" 

# 25 requests per 10 seconds
simple = { limit = 25, period = 10 }

[placement]
mode = "smart"