name = "cf-ai-backend"
main = "src/index.ts"
compatibility_date = "2024-02-23"
compatibility_flags = ['nodejs_compat']

[[vectorize]]
binding = "VECTORIZE_INDEX" # available within your Worker on env.VECTORIZE_INDEX
index_name = "supermem-vector-1"

[ai]
binding = "AI"

[[queues.producers]]
 queue = "batch-vector-queue"
 binding = "MY_QUEUE"

 [[queues.consumers]]
 queue = "batch-vector-queue"

[[kv_namespaces]]
binding = "SUPERMEMORY_KV"
id = "12dc3096052c42959bdaf29eaa3bc29e"
preview_id = "9aa453e040674566a756f0685433126e"

[browser]
binding = "MYBROWSER"

[placement]
mode = "smart"
